import turtle
tr = turtle.Turtle()
tr.pensize(5)
tr.color("blue")
tr.penup()
tr.goto(-100, -25)
tr.pendown()
tr.circle(45)
tr.color("black")
tr.penup()
tr.goto(0, -25)
tr.pendown()
tr.circle(45)
tr.color("red")
tr.penup()
tr.goto(100, -25)
tr.pendown()
tr.circle(45)
tr.color("yellow")
tr.penup()
tr.goto(-50, -75)
tr.pendown()
tr.circle(45)
tr.color("green")
tr.penup()
tr.goto(50, -75)
tr.pendown()
tr.circle(45)
turtle.done()